go_import_path: github.com/anmil/quicknote

language: go
go:
  - 1.8
  - master

os:
  - linux
  - osx

branches:
  only:
  - master
  - dev

matrix:
  fast_finish: true

install:
  - go get ./...

script:
  - go test -v -run Unit ./...
