go_import_path: github.com/anmil/quicknote

language: go
go:
  - 1.8
  - master

os:
  - linux
  - osx

matrix:
  fast_finish: true

install:
  - go get ./...

script:
  - go install github.com/anmil/quicknote/cmd/qnote
