go_import_path: github.com/anmil/quicknote/cmd/qnote

language: go
go:
  - 1.7
  - 1.8
  - master

os:
  - linux
  - osx

install:
  - go get gopkg.in/olivere/elastic.v5
  - go get github.com/blevesearch/bleve
  - go get github.com/mattn/go-sqlite3
  - go get github.com/fatih/color
  - go get github.com/spf13/viper
  - go get github.com/spf13/cobra
  - go get github.com/PuerkitoBio/goquery

script:
  - go build github.com/anmil/quicknote/cmd/qnote
